services:
  postgres:
    image: postgres:16
    container_name: ax-postgres
    environment:
      POSTGRES_DB: ax_company
      POSTGRES_USER: axuser
      POSTGRES_PASSWORD: axpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: